import { Noto_Sans, Pacifico  } from "next/font/google";
import "./globals.css";

const noto = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-noto',
});

const pacifico = Pacifico({
  subsets: ['latin'],
  weight: '400',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={noto.className}
      >
        {children}
      </body>
    </html>
  );
}
